name: Release Web Console

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Docker image with released git tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Build Docker image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          context: ./web_console
          username: fedlearner
          password: "${{ secrets.DOCKER_REGISTRY }}"
          image_name: fedlearner/fedlearner-web-console-test
          image_tag: latest
          push_git_tag: true
